### ISSUE TITLE
Reveal card data by using token

### ISSUE THREAD

**Issue by shan-c** [vgs-samples/vgs-collect-show-react-native-demo#12]
Is there a way to reveal card data by using tokens. Also is there a way to style the vgs labels

**Comment by dmytrokhl** [comment]
Hi @shan-c , sorry for late reply.
Yes, card issuers can reveal tokens with [VGS Show SDK](https://www.verygoodsecurity.com/docs/vgs-show). Check the example [here](https://github.com/vgs-samples/vgs-collect-show-react-native-demo/tree/master/ios/AwesomeProject/ShowWrappers).
