### ISSUE TITLE
 how to configure it in already existing project

### ISSUE THREAD

**Issue by beqramo** [vgs-samples/vgs-collect-show-react-native-demo#13]
Hi,

Please add flow on how it can be added to the already existing project.

Thanks

**Comment by dmytrokhl** [comment]
Hi @beqramo , unfortunately VGS doesn't provide RN SDK. This project is only example on how to use `VGS Collect` and  `VGS Show` native SDKs in RN. So if you use Collect SDK you can check example on how to create Collect wrapper [here](https://github.com/vgs-samples/vgs-collect-show-react-native-demo/tree/master/ios/AwesomeProject/CollectWrappers) or if you use Show SDK, the wrapper example can be found [here](https://github.com/vgs-samples/vgs-collect-show-react-native-demo/tree/master/ios/AwesomeProject/ShowWrappers).

**Comment by dmytrokhl** [comment]
Also soon we plan to make updates for RN demo app.

**Comment by beqramo** [comment]
Thank for your answer, my problem is as JS developer I don't know how to integrate that packages

**Comment by dmytrokhl** [comment]
Probably our quick guide for native [iOS](https://www.verygoodsecurity.com/docs/vgs-collect/ios-sdk/integration#how-to-integrate-the-sdk) and [Android](https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/integration) could help you, alongside with our native demo apps: [iOS](https://github.com/verygoodsecurity/vgs-collect-ios/tree/master/demoapp)  and [Android](https://github.com/vgs-samples/android-sdk-demo).

**Comment by beqramo** [comment]
okay thanks will try to use it
