### ISSUE TITLE
Copy card number on Android device

### ISSUE THREAD

**Issue by tuanthaiquang-agilityio** [vgs-samples/vgs-collect-show-react-native-demo#14]
Hello @dmytrokhl ,

I have referenced your code, I still have 1 issue on Android. I want to copy the card number with the `copyToClipboard (VGSTextView.CopyTextFormat format)`. And I'm still looking for a solution. Can you add this to your example on Android?

Thank you so much!

**Comment by DmytroDm** [comment]
Hi @tuanthai-agilityio, we have added a code example of copy test function https://github.com/vgs-samples/vgs-collect-show-react-native-demo/commit/060aee648f4bce4b6ec87d36ae0683b5b79343fa, check it please, and notify if you need any help.

**Comment by tuanthaiquang-agilityio** [comment]
Hi @DmytroDm ,

Thank you for responding. It's really helpful.

Thank you so much!
