### ISSUE TITLE
Error - Trying to register two views with the same name

### ISSUE THREAD

**Issue by fansilva1991** [vgs-samples/vgs-collect-show-react-native-demo#2]
### Description

After installing the SDK, and when implementing it on my application, I'm always getting the following error every time my screen re-renders:

![Simulator Screen Shot - iPhone 13 - 2022-06-25 at 15 46 10](https://user-images.githubusercontent.com/4633618/175786663-e5f15bc5-3002-4bf4-82cb-493f67065669.png)

### Implementation

```javascript
var CardCollector = NativeModules.CardCollector;
var VGSManager = NativeModules.VGSManager;
var VGSShowManager = NativeModules.VGSShowManager;

/// Collect SDK UI Elements
const CardTextField = requireNativeComponent('VGSCardTextField');
const ExpDateTextField = requireNativeComponent('VGSExpDateTextField');

const Balance = () => {
...

return (
          <View>
            <CardNumberLabel style={{height: 50, margin: 8, fontSize: 16}} />
            <ExpDateLabel style={{height: 50, margin: 8}} />
            <TouchableOpacity
              onPress={() => {
                VGSShowManager.revealData(value => {
                  console.tron.log('value', value);
                });
              }}>
              <Text>Reveal</Text>
            </TouchableOpacity>
          </View>)
...
}
...
```

### Environment Info

```bash
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 64.35 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### VGS SDK Info

```ruby
  pod 'VGSCollectSDK', "1.7.11"
  pod 'VGSCollectSDK/CardIO', "1.7.11"
  pod 'VGSShowSDK', "1.0.4"
```

**Comment by fansilva1991** [comment]
@flor-master @AnnaKudriasheva @dmytrokhl any feedback on that issue?

**Comment by dmytrokhl** [comment]
@fansilva1991 it seems the issue comes from RN app, not from SDK. Try to log `vgscollect.textfields` to check if you don't create duplicated instances and assign them to VGSCollect during rendering.

**Comment by fansilva1991** [comment]
@dmytrokhl this comes from the RN app AFTER installing and using the bridge described in the repo. And this is happening by just following the tutorial provided at the repository step by step.

**Comment by dmytrokhl** [comment]
@fansilva1991 after updating RN to latest version I can confirm that we reproduce this issue in sample app. This issue happens since iOS doesn't have hot reload on runtime, so basically each time RN running reloading it creates new instances of native objects. The easiest way to get rid of error message is to press `r` button on your keyboard. 

The other option is to remove all calls of `requireNativeComponent` from App.js file and create a single wrappers instead:

``` js
// CardTextField.js file
import {NativeModules, requireNativeComponent} from 'react-native';
const CardTextField = requireNativeComponent('VGSCardTextField');
export default CardTextField;
```
In App.js you will only need to import new wrappers:
``` js
import CardTextField from './CardTextField';
import ExpDateTextField from './ExpDateTextField';
```
We will also book a time to update sample app soon.

**Comment by fansilva1991** [comment]
Thanks, @dmytrokhl. I will test this and let you know if it works.

**Comment by dmytrokhl** [comment]
@fansilva1991 you can find updated sample app on master now.

**Comment by fansilva1991** [comment]
@dmytrokhl, this fixed the issue! Thanks!

I will close it.
