### ISSUE TITLE
Javascript Alternative to the Native SDK

### ISSUE THREAD

**Issue by fansilva1991** [vgs-samples/vgs-collect-show-react-native-demo#3]
Hello VGS team,

I've been trying to integrate the VGS SDK to our react-native application in the last two weeks and have faced many issues with the integration and a lack of feedback on how to solve them.

Do you guys have an alternative that uses only javascript, mainly like the solution used by a react-web application? This would avoid many problems since VGS doesn't have a proper SDK for react-native; it only recommends manually bridging the native code.

Thanks for the support.

**Comment by dmytrokhl** [comment]
Hi @fansilva1991 , you can check [here](https://www.verygoodsecurity.com/docs/vgs-collect) available SDKs.
