### ISSUE TITLE
Displaying card information using VGS Show

### ISSUE THREAD

**Issue by fansilva1991** [vgs-samples/vgs-collect-show-react-native-demo#5]
Hi, 

We are implementing the VGS Show into our application and displaying the credit card information.

But I have a question, the sample doesn't show where we should use the token to display the credit card information ( since we only gonna use the VGS Show ).

We only provide the ```vaultId```, and when displaying the information, only call a function without any parameters:

```javascript
 VGSShowManager.revealData(value => {
      console.log(value);
 });
```

Could you guys please help us with how we can use the token to display the information?

( Mostly like on the web sdk, where we need to provide this information on the API call. See the example below). 

```javascript
const iframe = show.request({
      name: 'data-text',
      method: 'POST',
      path: '/post',
      payload: {'card_number': 'tok_sandbox_uTsYqMdZbjd8xgeSAivQxg'},
      htmlWrapper: 'text',
      jsonPathSelector: 'json.card_number'
});
```

Also, on the Android SDK for example, when submitting the data, we need to provide the related tokens as expected ( see [example](https://github.com/vgs-samples/vgs-collect-show-android-react-native-demo/blob/master/App.js) below ):

```javascript
var data = {
        payment_card_holder: cardHolderToken,
        payment_card_number: cardNumberToken,
        payment_card_expiration_date: expireDateToken,
        payment_card_cvv: cvvToken,
};
VGSShow.submitAsync(data);
```

**Comment by fansilva1991** [comment]
@dmytrokhl @flor-master @AnnaKudriasheva any updates on this issue?

**Comment by dmytrokhl** [comment]
@fansilva1991 it works similar as in Android, you should[ pass payload dictionary](https://github.com/vgs-samples/vgs-collect-show-ios-react-native-demo/blob/master/ios/AwesomeProject/ShowWrappers/VGSShowManager.swift#L57) into `vgsShow.request(_:)`.  In sample app we use `SharedConfig.shared.payload` just to store tokens that we create with Collect SDK [here](https://github.com/vgs-samples/vgs-collect-show-ios-react-native-demo/blob/master/ios/AwesomeProject/CollectWrappers/VGSCollectManager.swift#L113) and then reuse them in Show SDK.

**Comment by fansilva1991** [comment]
@dmytrokhl, but by placing the payload at the SharedConfig, on the native code, don't you agree that this is impossible to update this from the javascript code accessed by the React Native application?

Can't you guys update the implementation to work like the Android one, that is:

```javascript
  const revealData = () => {
    try {
      var data = {
        payment_card_holder: cardHolderToken,
        payment_card_number: cardNumberToken,
        payment_card_expiration_date: expireDateToken,
        payment_card_cvv: cvvToken,
      };
      VGSShow.submitAsync(data);
    } catch (e) {
      console.log('revealData error', e);
    }
  };
```

Because without this, we can't use this implementation for the React Native application since it is impossible to update ``` SharedConfig.shared.payload``` from the Javascript code ( also because we are only using the Show SDK, since our backend is returning the tokens instead of using the Collect SDK).

Could you guys please help us with that?

**Comment by dmytrokhl** [comment]
> we can't use this implementation for the React Native application

Unfortunately VGS don't have official React Native SDK or bridge yet. This implementation - is [only a sample app](https://github.com/vgs-samples/vgs-collect-show-ios-react-native-demo#vgs-collect-ios-sdk---react-native-demo) on how to create RN<->Native bridges. This is customers responsibility to create bridge and expose attributes which they need in RN. We will check if we could add updates to sample app.

Regarding your question, you don't need to update `SharedConfig.shared.payload`. Basically what you are asking, is how to send json object to native code, you can check [example here](https://stackoverflow.com/a/53413340).

**Comment by fansilva1991** [comment]
@dmytrokhl, your solution worked! Thank you very much.

One last question. 

My reveal function looks like this right now.

```swift
  @objc
  func revealData(_ payload: NSDictionary, callback: @escaping RCTResponseSenderBlock) {
    DispatchQueue.main.async { [weak self] in

      let payloadDictionary = payload as? [String: Any]

      // Send data to your Vault
      self?.vgsShow.request(path: "/post", method: .post, payload: payloadDictionary, completion: { result in
        switch result {
        case .success(let code):
          callback([code])
        case .failure(let code, let error):
          let text = error?.localizedDescription ?? "Error"
          print("error! code: \(code))")
          callback([text])
          break
        }
      })
    }
  }
```

Do you know if by only sending the payloadDictionary, it will work for the vgsShow.request as the payload attribute? Or should we convert this to another type of object? ( On the JS side, I'm sending a JSON object ).

**Comment by dmytrokhl** [comment]
@fansilva1991 your code looks correct, `vgsShow.request` expects `[String:Any]` as payload and you convert `NSDictionary` at this line of code: 
```
let payloadDictionary = payload as? [String: Any]
```
