### ISSUE TITLE
How to customize font size, family, remove the border

### ISSUE THREAD

**Issue by fansilva1991** [vgs-samples/vgs-collect-show-react-native-demo#6]
Using the current implementation available in the example, there are no clear instructions about how to customize the font size and font family and remove the text's border for the components provided (CardNumberLabel, ExpDateLabel).

I've tried to adjust this using the React Native styles, but without success.

Could you please provide an example of how to do this?

Also, there is any chance of providing a component that works mostly like the android one? Where we have the generic field component:

```javascript
<VGSTextView
            style={styles.showSmallField}
            hint={'Holder'}
            contentPath={'json.payment_card_holder'}
            corners={12}
            fontSize={12}
          />
```

And provide the content path to define which field we are using. Because right now, we need to create custom native code for each new field we need to expose using VGS Show, which is not a best practice for a React Native implementation.

**Comment by dmytrokhl** [comment]
Unfortunately VGS don't provide yet official RN bridging SDK, this is customer's responsibility to build bridges or use native code. 

You have two options - style the views with native code([example](https://www.verygoodsecurity.com/docs/vgs-show/ios-sdk/ui-components#code-example-1)), or expose UI attributes to RN([example](https://reactnative.dev/docs/native-components-ios#styles)).
